name: Turn on Azure VM
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 1" # Runs every Monday at 00:00 AM UTC
permissions:
  id-token: write
  contents: read
jobs:
    turn-on-azure-vm:
        runs-on: ubuntu-latest
        steps:
        - name: Azure Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        - name: Start Azure VM
          id: start-vm
          uses: azure/cli@v2
          with:
            azcliversion: latest
            inlineScript: |
                which curl || sudo apt-get install curl -y
                # output="VM was not deallocated, so it was not started."
                # status=$(az vm get-instance-view --name ${{ vars.VM_NAME }} --resource-group ${{ vars.RESOURCE_GROUP }} --query 'instanceView.statuses[1].displayStatus' --output tsv)
                # if [ "$status" = "VM deallocated" ]; then
                #   az vm start --name ${{ vars.VM_NAME }} --resource-group ${{ vars.RESOURCE_GROUP }} --subscription ${{ vars.SUBSCRIPTION_ID }}
                #   output="VM is staring!"
                # fi
                # curl -v POST -H "Authorization: bearer ${{ secrets.GH_PAT }}" -H "Content-Type: application/json" -d '{"query": "mutation { addDiscussionComment(input: {body: \"'$output'\" discussionId: \"D_kwDOMED81c4AZ01H\" clientMutationId: \"1234\"}) { clientMutationId comment { id body } } }"}' https://api.github.com/graphql
                # echo "$output"