name: Turn off Azure VM
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 6" # Runs every Saturday at 00:00 AM UTC
permissions:
  id-token: write
  contents: read
jobs:
    turn-off-azure-vm:
        runs-on: ubuntu-latest
        steps:
        - name: Azure Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        - name: Stop Azure VM
          id: stop-vm
          uses: azure/cli@v2
          with:
            azcliversion: latest
            inlineScript: |
                output="VM was not running, so it was not stopped."
                status=$(az vm get-instance-view --name ${{ vars.VM_NAME }} --resource-group ${{ vars.RESOURCE_GROUP }} --query 'instanceView.statuses[1].displayStatus' --output tsv)
                if [ "$status" = "VM running" ]; then
                  az vm deallocate --name ${{ vars.VM_NAME }} --resource-group ${{ vars.RESOURCE_GROUP }} --subscription ${{ vars.SUBSCRIPTION_ID }}
                  output="VM is stopping!"
                fi
                curl -v POST -H "Authorization: bearer ${{ secrets.GH_PAT }}" -H "Content-Type: application/json" -d '{"query": "mutation { addDiscussionComment(input: {body: \"'$output'\" discussionId: \"D_kwDOMED81c4AZ01H\" clientMutationId: \"1234\"}) { clientMutationId comment { id body } } }"}' https://api.github.com/graphql
                echo "$output"